name: alpha
description: Flutter Project Template

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  # My-Dependencies
  provider: ^6.0.1
  shared_preferences: ^2.0.9
  hexcolor: ^2.0.5
  firebase_core: ^1.11.0
  firebase_auth: ^3.3.5
  google_sign_in: ^5.2.1
  cloud_firestore: ^3.1.6
  firebase_storage: ^10.2.5
  connectivity: ^3.0.6
  global_snack_bar: ^0.0.12
  flutter_form_builder: ^7.0.0
  form_builder_image_picker: ^2.0.0
  page_transition: ^2.0.4
  cached_network_image: ^3.2.0
  truncate: ^3.0.1
  uuid: ^3.0.6
  loader_overlay: ^2.0.5


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  # My-Dependencies
  flutter_launcher_icons: ^0.9.2
  flutter_native_splash: ^1.3.1
  easy_localization: ^3.0.0
  change_app_package_name: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/translations/

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/images/splash_logo.png
  color_dark: "#FFFFFF"
  image_dark: assets/images/splash_logo.png
  fullscreen: true

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo_icon.png"
