// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgr8gYTobiM5MOgdRexyRmExdL8ztOfWk',
    appId: '1:476543421951:android:036c921e2160abf858abca',
    messagingSenderId: '476543421951',
    projectId: 'basardalal-77b98',
    storageBucket: 'basardalal-77b98.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2fgvasEakULC_06lDGpvNzqcyrOry8MI',
    appId: '1:476543421951:ios:a48a698d42ae5ae158abca',
    messagingSenderId: '476543421951',
    projectId: 'basardalal-77b98',
    storageBucket: 'basardalal-77b98.appspot.com',
    androidClientId: '476543421951-5of0utffdn5mald5pk7kb0a4ul72fiue.apps.googleusercontent.com',
    iosClientId: '476543421951-br6ab21683so60juivv4vjsmf3vmihj9.apps.googleusercontent.com',
    iosBundleId: 'com.greedyrain.auction',
  );
}
